trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: yarn install
  displayName: 'yarn install'

- script: yarn build
  displayName: 'yarn build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: www'
  inputs:
    PathtoPublish: ./wwwroot/
    ArtifactName: www