# Header
menu:
  Home: /
  Archives: /archives
  Songs: /categories/Songs
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- tagcloud
- ads
- recent_songs
- recent_posts
- category
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 'UA-36145597-1'
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:
disqus_shortname: 'thewizardsmanse'
