name: Google Firebase CI Deploy

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:


jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16'
    - run: yarn --frozen-lockfile --non-interactive --prefer-offline
    - run: yarn build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        

