name: Google Firebase CI Deploy

on:
  push:
    branches:
      - master
      - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: yarn --frozen-lockfile --non-interactive --prefer-offline
    - run: yarn build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

